version: '3.7'

services:
  db:
    container_name: netology_orm_migrations
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env
